import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider"; // ✅ IMPORT YOUR CONTEXT PROVIDER
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Interview Schedule Voice Agent",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ WRAP CHILDREN WITH <Provider> */}
        <Provider>
          
          {children}
          <Toaster/>

        </Provider>
      </body>
    </html>
  );
}
